### PR TITLE
Update to v1.8.1

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@barthalion anything specific I can do to bypass this (since it makes no sense in this case)

```
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions com.github.tchx84.Flatseal.json'
 using PTY: False
{
    "errors": [
        "finish-args-unnecessary-xdg-data-access"
    ]
}
```

**Comment by Erick555** [comment]
Below the error it says:

> If you think problems listed above are a false positive, please report it here:
>   https://github.com/flathub/flatpak-builder-lint

**Comment by tchx84** [comment]
@barthalion oh, I figure it out.. https://github.com/flathub/flatpak-builder-lint/pull/52

**Comment by tchx84** [comment]
bot, build

**Comment by tchx84** [comment]
bot, build

**Comment by tchx84** [comment]
bot, build

**Comment by tchx84** [comment]
@barthalion  @Erick555 thanks for the tips and review ;)

**Pull request merged**
