### PR TITLE
Update runtime to 41

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Flatseal seems to work fine with the new runtime. @tchx84 Feel free to merge this PR. :-)

**Comment by tchx84** [comment]
@FakeShemp @AsciiWolf please check the README! and send this PR to the upstream flatpak manifest.

**Comment by AsciiWolf** [comment]
Oops, sorry. :-)

**Comment by AsciiWolf** [comment]
https://github.com/tchx84/Flatseal/pull/332

**Pull request closed without merging**
