### PR TITLE
GNOME 3.38 and other minor elements

### PR DESCRIPTION
**Pull request by Eonfge**
- Add .gitignore
- Update runtime to GNOME 3.38
- Update dependencies

### CODE REVIEW

**Comment by Eonfge** [comment]
@tchx84 Does this look good to you?

**Comment by tchx84** [comment]
hey @Eonfge, can you send some of these changes upstream first ?

I already migrated to libhandy 1 there (which required more than just bumping the version).

EDIT: I am planning for a new release soon btw, so if we upstream first, these will be included in the next release anyway.

**Comment by Eonfge** [comment]
Hey, no problem. I'll make a pull request. You want both changes on different branches, or is one good for you?

**Comment by tchx84** [comment]
> Hey, no problem. I'll make a pull request. You want both changes on different branches, or is one good for you?

One PR is fine, different commits per lib/runtime if you feel like it :)

**Comment by Eonfge** [comment]
:sunglasses: https://github.com/tchx84/Flatseal/pull/146

**Comment by tchx84** [comment]
Merged upstream PR.

**Pull request closed without merging**
