### PR TITLE
Workaround for Xorg/x11 issue

### LINKED ISSUE #23: Flatseal doesn't launch on GNOME Xorg
https://github.com/tchx84/Flatseal/issues/157

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Fix https://github.com/flathub/com.github.tchx84.Flatseal/issues/23

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
It works OOTB now

**Comment by bilelmoussaoui** [comment]
That's not a fix, Flatseal is a wayland compatible application, so x11 is a fallback.

**Comment by TheEvilSkeleton** [comment]
Weird. The current settings didn't work for me. It only worked when I run:

```bash
flatpak run --nosocket=fallback-x11 --socket=x11 com.github.tchx84.Flatseal
```

or by launching https://github.com/flathub/com.github.tchx84.Flatseal/pull/24#issuecomment-709643382.

**Comment by tchx84** [comment]
I can launch flatseal under X11, but there seems to be an underlying (system-level) issue that requires a full restart to make it work, e.g. when you switch from Wayland to X11 during the same "session".

Anyway, if that doesn't work for you, feel free to move this issue to the upstream repo.

**Pull request closed without merging**
